### ISSUE TITLE
When will you upload all the code?

### ISSUE THREAD

**Issue by zhangchbin** [Daniel-xsy/RoboBEV#1]

**Comment by Daniel-xsy** [comment]
This repo is working in the process. We need to check the official `nuScenes` license before we can release the `nuScenes-C` dataset. You can follow the [`CREATE.md`](https://github.com/Daniel-xsy/RoboBEV/blob/master/docs/CREATE.md) to generate your own corruption sets (it might take a bit long time). If the dataset is prepared, all the models in [`./zoo`](https://github.com/Daniel-xsy/RoboBEV/tree/master/zoo) should be able to run.

**Comment by jonyzhang2023** [comment]
> This repo is working in the process. We need to check the official `nuScenes` license before we can release the `nuScenes-C` dataset. You can follow the [`CREATE.md`](https://github.com/Daniel-xsy/RoboBEV/blob/master/docs/CREATE.md) to generate your own corruption sets (it might take a bit long time). If the dataset is prepared, all the models in [`./zoo`](https://github.com/Daniel-xsy/RoboBEV/tree/master/zoo) should be able to run.

looks like you did not upload 'from imagecorruptions import corrupt' on [corruptions.py](https://github.com/Daniel-xsy/RoboBEV/blob/master/corruptions/project/mmdet3d_plugin/corruptions.py), is there anyway i can use it? I got a hurry job to use robobev pls.

**Comment by Daniel-xsy** [comment]
@jonyzhang2023 You can install it through `pip install imagecorruptions` as it's a third-party package.

**Comment by Daniel-xsy** [comment]
Just to provide more information. Our dataset is built with the following configuration:
```
corruptions = [dict(type='CameraCrash', easy=2, mid=4, hard=5),
               dict(type='FrameLost', easy=2, mid=4, hard=5),
               dict(type='MotionBlur', easy=2, mid=4, hard=5)],
               dict(type='ColorQuant', easy=1, mid=2, hard=3)],
               dict(type='Brightness', easy=2, mid=4, hard=5)],
               dict(type='LowLight', easy=2, mid=3, hard=4)],
               dict(type='Fog', easy=2, mid=4, hard=5)],
               dict(type='Snow', easy=1, mid=2, hard=3)]
]
```

**Comment by Daniel-xsy** [comment]
Feel free to reach out and re-open this issue if you have any questions :)
