### ISSUE TITLE
nuScenes-C dataset

### ISSUE THREAD

**Issue by haoshuai714** [Daniel-xsy/RoboBEV#11]
How to download nuScenes-C dataset? I did not find the relevant data set in this link https://opendatalab.com/OpenDataLab/nuScenes-C.Thanks!

**Comment by Daniel-xsy** [comment]
The link works on my side: https://opendatalab.com/OpenDataLab/nuScenes-C.

Maybe you can visit OpenDataLab's official [website](https://opendatalab.com/home) and search nuScenes-C manually.

**Comment by haoshuai714** [comment]
Thanks！ The OpenDataLab's official [website](https://opendatalab.com/home) is empty.

**Comment by haoshuai714** [comment]
> Thanks！ The OpenDataLab's official [website](https://opendatalab.com/home) is empty.

I can't find the download link for the nuscenes-c dataset.

**Comment by Daniel-xsy** [comment]
What about this one: https://opendatalab.com. You can search here:
<img width="1151" alt="image" src="https://github.com/Daniel-xsy/RoboBEV/assets/66255889/5f52d0dc-b9d2-4e69-841c-44061c8892c5">

**Comment by haoshuai714** [comment]
> What about this one: https://opendatalab.com. You can search here: <img alt="image" width="1151" src="https://private-user-images.githubusercontent.com/66255889/294416747-5f52d0dc-b9d2-4e69-841c-44061c8892c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzgwODUsIm5iZiI6MTcwNDQzNzc4NSwicGF0aCI6Ii82NjI1NTg4OS8yOTQ0MTY3NDctNWY1MmQwZGMtYjlkMi00ZTY5LTg0MWMtNDQwNjFjODg5MmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2NTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNzQ4ZjM3NmU4NThmNDU1MDI3OTcxOWEwZThmOTQ1OWYzODFlZDM2ZTJlODcyNzFkODc1YTU5OThkOTE0NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HrI07zt7Bv76OcsHEdOY5kJHgMOsTgBRAlCiBkRKEcw">

https://opendatalab.com/OpenDataLab/nuScenes-C This link is empty, not upload this dataset.

**Comment by Daniel-xsy** [comment]
Sorry for the misunderstanding! Please click “数据集文件” and you can find it inside the `raw/image` folder. The `raw/pointcloud` is used for [Robo3D](https://github.com/ldkong1205/Robo3D)

**Comment by haoshuai714** [comment]
> Sorry for the misunderstanding! Please click “数据集文件” and you can find it inside the `raw/image` folder. The `raw/pointcloud` is used for [Robo3D](https://github.com/ldkong1205/Robo3D)

Thanks you very much! I get it.
