### ISSUE TITLE
AssertionError: Samples in split doesn't match samples in predictions.

### ISSUE THREAD

**Issue by Slonna** [Daniel-xsy/RoboBEV#15]
Hi, when I use the natural coruptions for evaluating trained 3d detector's robustness , I meet this error below which I can not find the reason.
Apart from the test pipeline need to be revised（I have finished) , does the ann_file need to be revise accordingly?

![企业微信截图_a938a42a-3a6c-4cc2-a3fb-90b40ae5f3fd](https://github.com/user-attachments/assets/99901b87-c939-4193-9025-99514b7fb5e9)

**Comment by Slonna** [comment]
It seems the prediction samples number is lower than the gt , but I do not know what lead to this? 
![image](https://github.com/user-attachments/assets/2d4da7f4-c7de-4687-9561-8994d2435334)

**Comment by Daniel-xsy** [comment]
Hi, to evaluate the model robustness on nuScenes-C dataset, the `ann_file` is the same as evaluating on the standard nuScenes dataset.

In the second screenshot you provided, it's weird the number of `Start to convert detection format...` (**5480**) is different from the progress bar above (**6019**). I suggest you set a breakpoint in the middle to debug what's happening there. The evaluation size should be **6019** for nuScenes (and nuScenes-C) validation set.

**Comment by Slonna** [comment]
Thanks for your swift reply.

**Comment by clever-mood** [comment]
> Thanks for your swift reply.

"I'd like to ask if you have resolved this error: AssertionError: Samples in split don't match samples in predictions."
