### ISSUE TITLE
HI , Does Nuscenes-C have the corruption data corresponding to original nuscenes sweeps data?

### ISSUE THREAD

**Issue by Slonna** [Daniel-xsy/RoboBEV#16]

**Comment by Daniel-xsy** [comment]
Hi @Slonna ,

Unfortunately, we only have corruption data for `sample`, not `sweeps` since having corrupted `sweeps` data would require much larger storage. The current nuScenes-C dataset already takes around 260 GB of space.

**Comment by Slonna** [comment]
Ok ,Thanks for your kind reply
