### ISSUE TITLE
nuscenes-c generate failed

### ISSUE THREAD

**Issue by jonyzhang2023** [Daniel-xsy/RoboBEV#2]
when I use 'bash tools/generate_dataset.sh', it raised an error:
`img file does not exist: ./data/nuscenes/samples/CAM_FRONT/n015-2018-07-11-11-54-16+0800__CAM_FRONT__1531281439762460.jpg`
Actually I do have this file in my path. And it seems like find another file path in my mmdet3d location. It still use loading.py from mmdet3d rather than custom [pipeline](https://github.com/Daniel-xsy/RoboBEV/blob/master/corruptions/project/mmdet3d_plugin/datasets/pipelines/custom_loading.py)

But I have already changed the config file dataset path and changed the PYTHONPATH in generate_dataset.sh. How can I fix it?

**Comment by Daniel-xsy** [comment]
I can run it successfully on my side. When running `bash tools/generate_dataset.sh`, you are expected in the `./corruptions` folder. However, according to the error information, it seems to look for images within the `./corruptions` folder. Please make sure the `data_root` in the config is correct.

If the above is correct, this might be caused by `nuscenes_infos_val.pkl`. nuScenes dataset path cannot be changed after you generate it, because it will save the image path the time you generate it. You can load it to check if the path is correct.

**Comment by Daniel-xsy** [comment]
Yes, when generating the `nuScenes-C` dataset, it will use original loading, not custom loading. The latter is only used when benchmarking models.

**Comment by jonyzhang2023** [comment]
when I remove all the exciting pkl file in my dataroot, it raised that `' No such file or directory: nuscenes_infos_temporal_val.pkl',` when I link 'nuscenes_infos_temporal_val.pkl' again , it comes that `img file does not exist: ./data/nuscenes/samples/CAM_FRONT/n015-2018-07-11-11-54-16+0800__CAM_FRONT__1531281439762460.jpg `. which is not the dataroot I wrote in config, how can I fix it ?

**Comment by Daniel-xsy** [comment]
How do you generate `nuscenes_infos_temporal_val.pkl`? I think the problem might be in this file.

**Comment by jonyzhang2023** [comment]
I used bevdet data generation, in which I want to test it profermance.
So what is the right anno data in [anno_root](https://github.com/Daniel-xsy/RoboBEV/blob/master/corruptions/project/config/nuscenes_c.py#L20)?

**Comment by Daniel-xsy** [comment]
It depends on the model you want to test. If you want to test `BEVDet`, just need to follow it's repo to generate the `.pkl` file. You can use the following script to debug and check whether the image path in it is wrong.
```python
import pickle
import os
import mmcv

# the annotation root, change it to your own
anno_path = '/nvme/konglingdong/models/RoboDet/data/nuscenes_infos_val_4d_interval3_max60.pkl'
data_root = '/nvme/share/data/sets/nuScenes/samples'
# save path of the correct anno file
save_path = '/nvme/konglingdong/models/RoboDet/data/nuscenes_infos_val_4d_interval3_max60_custom.pkl'

def main():

    with open(anno_path, 'rb') as f:
        anno = pickle.load(f)
    
    prog_bar = mmcv.ProgressBar(len(anno['infos']))
    for i in range(len(anno['infos'])):
        for sensor in anno['infos'][i]['cams'].keys():
           # check weather filename here is correct
            filename = os.path.split(anno['infos'][i]['cams'][sensor]['data_path'])[1]
            anno['infos'][i]['cams'][sensor]['data_path'] = os.path.join(data_root, sensor, filename)
        prog_bar.update()
    
    with open(save_path, 'wb') as f:
        pickle.dump(anno, f)

if __name__=='__main__':
    main()
```

**Comment by Daniel-xsy** [comment]
Additionally, please check if you can run `BEVDet` on clean nuScenes dataset using `tools/dist_test.sh`. If so, the problem might not caused by the  `nuscenes_c.py` config

**Comment by jonyzhang2023** [comment]
it shows good 
`[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 5026.3 task/s, elapsed: 1s, ETA:     0s`
so maybe I need to modify [anno_file](https://github.com/Daniel-xsy/RoboBEV/blob/master/corruptions/project/config/nuscenes_c.py#L47) from `nuscenes_infos_temporal_val.pkl` to `nuscenes_infos_val_4d_interval3_max60.pkl`?

**Comment by Daniel-xsy** [comment]
Actually, the name doesn't matter. If you set the `data_root` in the above script correctly, you can try using the newly generated anno file. Also, please check this https://github.com/Daniel-xsy/RoboBEV/issues/2#issuecomment-1454743557.

**Comment by jonyzhang2023** [comment]
I use this [test ](https://github.com/Daniel-xsy/RoboBEV/issues/2#issuecomment-1454738883) and it shows good, so why I can not generate nuscenes-c? I am confused now ..  I use the same dataroot

**Comment by Daniel-xsy** [comment]
Please set a breakpoint here: https://github.com/Daniel-xsy/RoboBEV/blob/7c8b8d80678d818ee26a1548aad13b64b6d17eac/corruptions/project/mmdet3d_plugin/datasets/custom_nuscenes_dataset.py#L128

A simple work around: change the filepath manually here to the correct one.

**Comment by jonyzhang2023** [comment]
Thanks for your kindness response, I just manually moditied here and it works now.

**Comment by Daniel-xsy** [comment]
I'm glad to hear that. we are sorry this repo is working in process and some parts haven't been well-organized. we will organize it later.
