### ISSUE TITLE
visualization results

### ISSUE THREAD

**Issue by jonyzhang2023** [Daniel-xsy/RoboBEV#3]
Hi, is there any way I can plot the results demo on RoboBEV based on my modal detection results?

**Comment by Daniel-xsy** [comment]
You can refer to [this](https://github.com/Daniel-xsy/RoboBEV/blob/master/zoo/BEVFormer/tools/analysis_tools/visual.py), I'm not sure if there are some bugs since I haven't used it for some time.

**Comment by Daniel-xsy** [comment]
We haven't develop visualization tool custom for RoboBEV, Maybe you can corrupt the image manually after loading.

**Comment by jonyzhang2023** [comment]
I see, thx for your kindness help!

**Comment by jonyzhang2023** [comment]
I follow the readme file to use the custom loding, but it comes fault on [#results](https://github.com/Daniel-xsy/RoboBEV/blob/master/corruptions/project/mmdet3d_plugin/datasets/pipelines/custom_loading.py#L57), I have sent you a email could you please check it?
